export default {
  default: ({ MM, DD, yyyy }) => `${MM}/${DD}/${yyyy}`,
  ISO: ({ moment }) => moment.toISOString(),
  localeDateShort: ({ l }) => l,
  localeDate: ({ L }) => L,
  localeTimeShort: ({ LT }) => LT,
  localeTime: ({ LTS }) => LTS,
  'h:mm tt': ({ h, mm, tt }) => `${h}:${mm} ${tt}`,
  'M/D': ({ M, D }) => `${M}/${D}`,
  'M/D/yyyy': ({ M, D, yyyy }) => `${M}/${D}/${yyyy}`,
  'MM/DD/yyyy': ({ MM, DD, yyyy }) => `${MM}/${DD}/${yyyy}`,
  'M/D/yyyy h:mm tt': ({ M, D, yyyy, h, mm, tt }) => `${M}/${D}/${yyyy} ${h}:${mm} ${tt}`,
  'MM/DD/yyyy h:mm tt': ({ MM, DD, yyyy, h, mm, tt }) => `${MM}/${DD}/${yyyy} ${h}:${mm} ${tt}`,
  'MMMM D, yyyy': ({ MMMM, D, yyyy }) => `${MMMM} ${D}, ${yyyy}`,
};
