export default {
  default: ({ MM, DD, YYYY }) => `${MM}/${DD}/${YYYY}`,
  moment: ({ moment }) => moment,
  jsDate: ({ date }) => date,
  ISO: ({ moment }) => moment.toISOString(),
  localeDateShort: ({ l }) => l,
  localeDate: ({ L }) => L,
  localeTimeShort: ({ LT }) => LT,
  localeTime: ({ LTS }) => LTS,
  'h:mm A': ({ h, mm, A }) => `${h}:${mm} ${A}`,
  'M/D': ({ M, D }) => `${M}/${D}`,
  'M/D/YYYY': ({ M, D, YYYY }) => `${M}/${D}/${YYYY}`,
  'MM/DD/YYYY': ({ MM, DD, YYYY }) => `${MM}/${DD}/${YYYY}`,
  'M/D/YYYY h:mm A': ({ M, D, YYYY, h, mm, A }) => `${M}/${D}/${YYYY} ${h}:${mm} ${A}`,
  'MM/DD/YYYY h:mm A': ({ MM, DD, YYYY, h, mm, A }) => `${MM}/${DD}/${YYYY} ${h}:${mm} ${A}`,
  'MMMM D, YYYY': ({ MMMM, D, YYYY }) => `${MMMM} ${D}, ${YYYY}`,
};
