export default {
  default: v => v,
  abs: Math.abs,
  floor: Math.floor,
  ceil: Math.ceil,
  trunc: Math.trunc,
  round: Math.round,
  fixed: n => v => v.toFixed(n),
  fixed2: v => v.toFixed(2),
  percent3: v => `${(v * 100).toFixed(3)}%`,
  percent: n => v => `${(v * 100).toFixed(n)}%`,
  exponential2: v => v.toExponential(2),
  exponential: n => v => v.toExponential(n),
  usd: v => v.toLocaleString('en-US', { style: 'currency', currency: 'USD' }),
  locale: v => v.toLocaleString(),
  binary: v => Math.floor(v).toString(2),
  octal: v => Math.floor(v).toString(8),
  hex: v => Math.floor(v).toString(16),
  base: n => v => Math.floor(v).toString(n),
};
